### ISSUE TITLE
Kitura-OpenAPI shouldn't rely on Stencil

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura-OpenAPI#16]
Kitura-OpenAPI requires Stencil to allow customization of the swagger hosting path.  However, this means all projects now depend on Stencil (and all of its dependencies) which are 3rd party repositories, and as well as increasing build time, introduces some additional risk of breakage.

We could instead use a pattern matching approach (either regex or simple string search/replace) to perform the substitutions.

**Comment by djones6** [comment]
@ddunn2 could you take a look at this in the next week or so?

**Comment by ddunn2** [comment]
@djones6 I've opened a [PR](https://github.com/IBM-Swift/Kitura-OpenAPI/pull/19) for this if you could take a look. 
Thanks!

**Comment by ddunn2** [comment]
Merged.
