### ISSUE TITLE
The `openapi/ui` doesn't work correctly when using sub routing

### ISSUE THREAD

**Issue by ddunn2** [IBM-Swift/Kitura-OpenAPI#27]
Example code:

```swift
let router = Router()
let subrouter = Router()

func getAllBooks(user: AdminAuth, completion: @escaping ([Book]?, RequestError?) -> Void) {
    Book.findAll(completion)
}

subrouter.router.get("/books", handler: getAllBooks)

KituraOpenAPI.addEndpoints(to: subrouter)

router.all("/admin", middleware: subrouter)
```

Navigating to `localhost:8080/admin/openapi` works correctly however if you navigate to `localhost:8080/admin/openapi/ui` it errors, as it can't find the openapi definition. It seems to be looking at `localhost:8080/openapi`. 

Changing the explore search bar to `/admin/openapi` resolves this issue as it's pointing to the correct location.

**Comment by ianpartridge** [comment]
Agreed. This is a fundamental limitation of the OpenAPI support which was not designed with subrouters in mind. Think we should probably WONTFIX as it's very unlikely we'll be able to redesign this in the medium term...

**Comment by svanimpe** [comment]
I hit a similar issue. I use subrouters for prefixes as follows:

```swift
configureAPIRoutes(using: router.route("api"))
KituraOpenAPI.addEndpoints(to: router)
```

OpenAPI also doesn't pick up these routes. I'd expect this to work, given that the subrouter was created by the router I pass to OpenAPI.
