### ISSUE TITLE
Customize swaggerUIPath currently broken

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/Kitura-OpenAPI#8]
This is the error message which I get when following the README instructions on how to customize the endpoint paths: “Can’t read swagger JSON from http://localhost:8080/openapi” even though I’m at `http://localhost:8080/swagger/ui/`

Therefore I'm going to remove the following wording from the README under PR #7 (when this issue is fixed the wording below can be added back in):

If you wish, you can customize the endpoint paths:
```swift
let config = KituraOpenAPIConfig(apiPath: "/swagger", swaggerUIPath: "/swagger/ui")
KituraOpenAPI.addEndpoints(to: router, with: config)
```

**Comment by djones6** [comment]
@helenmasters I'm hoping this is now fixed by #10 - could you try on the latest tag (`1.1.0`)?

**Comment by djones6** [comment]
@helenmasters This is fixed, I have a sample project that customizes the swagger and swaggerui path: https://github.com/djones6/OpenAPIDemo/blob/master/Sources/Application/Application.swift#L36

This works locally for me.  Could you confirm, and then add the wording back in to the readme?

**Comment by helenmasters** [comment]
Tested and confirmed as fixed. Raised PR #21 to add the wording back into the README.

**Comment by helenmasters** [comment]
Closing as the issue is now fixed and the wording has been adding back in under PR #21.
